language: java
jdk: oraclejdk11

branches:
  only:
  - develop
  - master

before_install:
- chmod +x mvnw

deploy:
  provider: cloudfoundry
  username: polushan@yandex.ru
  api: https://api.run.pivotal.io
  organization: PingPong
  space: development
  manifest: manifest.yml
  app_name: discovery
  on:
    branch: master
  password:
    secure: nZV+5kpp7uaIWUc6ZrCTb1zjDnLUe38yBw4ib84uYPhHtWzWFNtsWfWnnk7Ef0Wt/s/kqLTbC8SpeAIaTScJOgbXEXcn7u7WYmXoeEqkAYv+xby7dgCdhwS275b29sfutkygGgWJjTtGarXARpZVj7YvZhl/z0Id6gzVCsqB6L8MA5IkYrbY3BudYdYCko+FUw8GfwwZeAtEIMg252K51iLZreAbFrozsHAv8a2EI4vR/t3HfwxLKSJgcgyPoh7hOFUefpG4hnhiNPpKAXmWIbB5dt7JhPjC2nHCWNR96DIgkctoP4OMo1IssgAuAB5UpW3h+vZ96DTsJi1X3MedtqT5xY0sOw926U3xq/+qNT4hMGRkIv0xQ/vSvJZJufuVeiSOLP1Bkdbr5jS6lkN+UEg+szrIrH7ozHMacLG9xE/n13MN3oMgotOSxbAmsrJRhazASgSVwVlRePWSgfO+ZirJ+6zDlFy9lu0khtnFxun+fYa/HtRw9Rxp0Bki7hZRrVq/4gVo/UUGISsrYEhFD5Fm83sLxIKk2zm5mOX9qSvYPPwAtfHVyGODF8EDZFZzWuGMA3bieRWalLAxarvjaCwMtW+6HydDjtaDCIkdIlEV5P7wDRqkIN2c3XwpjJIP7/HsUe9CIU/g8yKekJ0EKnYFIlM7EayhCHvLvR/i9PI=
